### PR TITLE
OCPBUGS-13926: add loglevel controller for  OCM-o

### PR DESCRIPTION
**Pull request by lance5890**
add loglevel controller for openshift-controller-manager-operator

### CODE REVIEW

**Comment by lance5890** [comment]
@atiratree @ingvagabund

**Review by atiratree — APPROVED** [review]

**Comment by atiratree** [comment]
looks good, thanks for the PR, but it should be tracked as a bugs since we should have been supporting this. But probably no backports are required since nobody complained so far as we have the v4 set.

**Pull request merged**
