### PR TITLE
Move default config to its own path

### PR DESCRIPTION
**Pull request by marun**
/cc @sttts

### CODE REVIEW

**Comment by adambkaplan** [comment]
@marun this can be squashed into a single commit.

Note that since we are past feature freeze, we need a Bugzilla to merge any PR.

**Comment by marun** [comment]
@adambkaplan If you care to have this fix in this release, maybe you could file the BZ? Otherwise it could wait. I'm just trying to be helpful here, not make work for myself or anyone else.

**Comment by marun** [comment]
/hold

Waiting for 4.5, this is not worth filing a bz for.

**Pull request merged**
