### PR TITLE
[release-4.6] Bug 1944145: Bump kubernetes to 0.19.9

### PR DESCRIPTION
**Pull request by coreydaley**
bumping kubernetes

### CODE REVIEW

**Comment by wewang58** [comment]
Checked job, no nil pointer dereference error, https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2518/pull-ci-openshift-machine-config-operator-master-e2e-aws-workers-rhel7/1382154484406292480
/lgtm

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.00

**Pull request merged**
