### PR TITLE
move v3.11.0 to v4.1.0

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by adambkaplan** [comment]
@mfojtik also update https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/master/manifests/03_config.cr.yaml ?

**Comment by mfojtik** [comment]
/hold

lets wait for release cut before merging this.

**Comment by adambkaplan** [comment]
@mfojtik bump (needs rebase)

**Pull request closed without merging**
