### PR TITLE
fix progressing condition logic

### PR DESCRIPTION
**Pull request by deads2k**
progressing is based on comparing the daemonset generation to itself and the operator generation to itself.  

@bparees flake fix
@sanchezl I think I found a better spot for the operator status generation ptal

### CODE REVIEW

**Comment by bparees** [comment]
thanks @deads2k

**Comment by deads2k** [comment]
removed fancy set of observed generation because it probably caused
```
"message": "daemonset/controller-manager: observed generation is 44, desired generation is 45.\nopenshiftcontrollermanageroperatorconfigs/instance: observed generation is 0, desired generation is 1.",
```

**Comment by vrutkovs** [comment]
This fixes BYOR install at least.

/retest

**Comment by deads2k** [comment]
merged to unstick us in the 3pm hour

**Comment by sttts** [comment]
:+1:

**Pull request merged**
