### PR TITLE
Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout

### PR DESCRIPTION
**Pull request by ingvagabund**
This repository uses the delegated authentication which has been identified to contain a bug that increases the number of watch requests against the Kube API server.

We provided a temporary branch that contains a fix and switched this repository to that branch.

With this change, k8s.io/apiserver points to temporary-watch-reduction-patch-1.21 to pick up k/k/pull/101102

Feel free to remove it once the upstream PR merges and a new Z release is cut.

### CODE REVIEW

**Comment by ingvagabund** [comment]
Before the change (`Watch close` every 10 seconds):

```
I0513 14:01:06.162132 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:06.162234 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:06.201601 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:07.421850 2630909 leaderelection.go:346] lock is held by openshift-controller-manager-operator-745bfcf9fb-ggp6z_db6d4288-af5b-421f-938d-e133aa4073f5 and has not yet expired
I0513 14:01:07.421900 2630909 leaderelection.go:248] failed to acquire lease openshift-controller-manager-operator/openshift-controller-manager-operator-lock
I0513 14:01:16.163183 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:16.163310 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:16.202371 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:18.116344 2630909 leaderelection.go:346] lock is held by openshift-controller-manager-operator-745bfcf9fb-ggp6z_db6d4288-af5b-421f-938d-e133aa4073f5 and has not yet expired
I0513 14:01:18.116410 2630909 leaderelection.go:248] failed to acquire lease openshift-controller-manager-operator/openshift-controller-manager-operator-lock
I0513 14:01:26.164216 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:26.164251 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:26.203436 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:31.883729 2630909 leaderelection.go:346] lock is held by openshift-controller-manager-operator-745bfcf9fb-ggp6z_db6d4288-af5b-421f-938d-e133aa4073f5 and has not yet expired
I0513 14:01:31.883787 2630909 leaderelection.go:248] failed to acquire lease openshift-controller-manager-operator/openshift-controller-manager-operator-lock
I0513 14:01:36.165381 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:36.165421 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:36.204583 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:45.351826 2630909 leaderelection.go:346] lock is held by openshift-controller-manager-operator-745bfcf9fb-ggp6z_db6d4288-af5b-421f-938d-e133aa4073f5 and has not yet expired
I0513 14:01:45.351853 2630909 leaderelection.go:248] failed to acquire lease openshift-controller-manager-operator/openshift-controller-manager-operator-lock
I0513 14:01:46.166447 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:46.166627 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:46.205484 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:56.167754 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:56.167835 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:01:56.206077 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:02:05.590285 2630909 leaderelection.go:346] lock is held by openshift-controller-manager-operator-745bfcf9fb-ggp6z_db6d4288-af5b-421f-938d-e133aa4073f5 and has not yet expired
I0513 14:02:05.590332 2630909 leaderelection.go:248] failed to acquire lease openshift-controller-manager-operator/openshift-controller-manager-operator-lock
I0513 14:02:06.168265 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:02:06.168444 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
I0513 14:02:06.206591 2630909 reflector.go:530] k8s.io/client-go@v0.21.0-rc.0/tools/cache/reflector.go:167: Watch close - *v1.ConfigMap total 0 items received
```

After the change:

```
I0513 14:04:23.805120 2631473 leaderelection.go:346] lock is held by openshift-controller-manager-operator-745bfcf9fb-ggp6z_db6d4288-af5b-421f-938d-e133aa4073f5 and has not yet expired
I0513 14:04:23.805144 2631473 leaderelection.go:248] failed to acquire lease openshift-controller-manager-operator/openshift-controller-manager-operator-lock
I0513 14:04:37.625146 2631473 leaderelection.go:346] lock is held by openshift-controller-manager-operator-745bfcf9fb-ggp6z_db6d4288-af5b-421f-938d-e133aa4073f5 and has not yet expired
I0513 14:04:37.625197 2631473 leaderelection.go:248] failed to acquire lease openshift-controller-manager-operator/openshift-controller-manager-operator-lock
I0513 14:04:58.638573 2631473 leaderelection.go:346] lock is held by openshift-controller-manager-operator-745bfcf9fb-ggp6z_db6d4288-af5b-421f-938d-e133aa4073f5 and has not yet expired
I0513 14:04:58.638626 2631473 leaderelection.go:248] failed to acquire lease openshift-controller-manager-operator/openshift-controller-manager-operator-lock
I0513 14:05:15.673000 2631473 leaderelection.go:346] lock is held by openshift-controller-manager-operator-745bfcf9fb-ggp6z_db6d4288-af5b-421f-938d-e133aa4073f5 and has not yet expired
I0513 14:05:15.673053 2631473 leaderelection.go:248] failed to acquire lease openshift-controller-manager-operator/openshift-controller-manager-operator-lock
I0513 14:05:32.943706 2631473 leaderelection.go:346] lock is held by openshift-controller-manager-operator-745bfcf9fb-ggp6z_db6d4288-af5b-421f-938d-e133aa4073f5 and has not yet expired
I0513 14:05:32.943732 2631473 leaderelection.go:248] failed to acquire lease openshift-controller-manager-operator/openshift-controller-manager-operator-lock
```

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
