### PR TITLE
add Ben as top level approver

### PR DESCRIPTION
**Pull request by deads2k**
/assign @bparees

### CODE REVIEW

**Comment by bparees** [comment]
pretty sure i can't actually approve/lgtm a PR that is adding me as an approver, or that would be a pretty big security hole.

**Comment by bparees** [comment]
i'm shocked and disappointed that worked.

**Comment by soltysh** [comment]
> i'm shocked and disappointed that worked.

The PR was already approved by David, you've only lgtm-ed. I'd be shocked if this was approved through you adding yourself there.

**Pull request merged**
