### PR TITLE
Revert #300 "API-1666: add image pull secret cleanup controller"

### PR DESCRIPTION
**Pull request by neisw**
Reverts #300 ; tracked by [TRT-1341](https://issues.redhat.com//browse/TRT-1341)

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

Suspect PR broke periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6  and periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of these jobs to confirm the fix has corrected the problem:

```
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6
```

CC: @sanchezl

<div align="right">
PR created by <a href="https://github.com/stbenjam/revertomatic">Revertomatic<sup>:tm:</sup></a>
</div>

### CODE REVIEW

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6

**Comment by neisw** [comment]
/hold

wait for payload-job results

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm

**Comment by neisw** [comment]
/hold cancel

Both periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-sdn-bm and periodic-ci-openshift-release-master-nightly-4.15-e2e-metal-ipi-ovn-ipv6 passed payload tests

**Review by sanchezl — APPROVED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
