### PR TITLE
BUILD-582, OCPBUGS-14638: bump(k8s): 1.27.1

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

### CODE REVIEW

**Comment by coreydaley** [comment]
/retest
infra issues

**Comment by ingvagabund** [comment]
```
I0607 03:59:09.149010       1 simple_featuregate_reader.go:171] Starting feature-gate-detector
E0607 03:59:09.151470       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:09.151538       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:09.156584       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:09.176930       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:09.217374       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:09.297615       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:09.458182       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:09.778926       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:10.419090       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:11.699814       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:14.260899       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:19.381809       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:29.622463       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 03:59:50.102984       1 simple_featuregate_reader.go:290] cluster failed with : unable to determine features: missing desired version "" in featuregates.config.openshift.io/cluster
E0607 04:00:09.148954       1 starter.go:114] timed out waiting for FeatureGate detection
W0607 04:00:09.148989       1 builder.go:106] graceful termination failed, controllers failed with error: timed out waiting for FeatureGate detection
```

**Comment by coreydaley** [comment]
/lgtm
/hold 
@ingvagabund All tests are passing so it looks good to me, feel free to remove the `hold` if you are good with it.
Thank you!
I will update the linked JIRAs, thank you for doing the work!

**Comment by ingvagabund** [comment]
```
I0607 14:33:59.826211       1 simple_featuregate_reader.go:171] Starting feature-gate-detector
I0607 14:33:59.828047       1 starter.go:112] FeatureGates initialized: knownFeatureGates=[...]
```

**Pull request merged**
