### PR TITLE
Bug 1821895: Bump k8s to 1.18 and openshift/* to master

### PR DESCRIPTION
**Pull request by soltysh**
/assign @mfojtik

### CODE REVIEW

**Comment by gabemontero** [comment]
so @adambkaplan this PR would render my PR https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/146 from last week unneeded, no?

**Comment by soltysh** [comment]
> so @adambkaplan this PR would render my PR #146 from last week unneeded, no?

@gabemontero you'd need to change what pieces are still missing, I haven't touched metrics bits and I see some changes to Dockerfiles in your PR which are not here. The most important bit is the `go.mod` changes, try to have very limited deps in `replace` directive, compare my PR with yours on that front. The problem with `replace` is that you need to remember to bump them manually and that's often forgotten, so only the ones you have 101% confidence should be there.

**Comment by gabemontero** [comment]
> > so @adambkaplan this PR would render my PR #146 from last week unneeded, no?
> 
> @gabemontero you'd need to check what pieces are still missing, I haven't touched metrics bits and I see some changes to Dockerfiles in your PR which are not here. The most important bit is the `go.mod` changes, try to have very limited deps in `replace` directive, compare my PR with yours on that front. The problem with `replace` is that you need to remember to bump them manually and that's often forgotten, so only the ones you have 101% confidence should be there.

I'll just keep this open then and see what is left after I have to rebase

**Comment by gabemontero** [comment]
> > > so @adambkaplan this PR would render my PR #146 from last week unneeded, no?
> > 
> > 
> > @gabemontero you'd need to check what pieces are still missing, I haven't touched metrics bits and I see some changes to Dockerfiles in your PR which are not here. The most important bit is the 

Yeah there are no top level Dockefile changes in https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/146  ... 

`go.mod` changes, try to have very limited deps in `replace` directive, compare my PR with yours on that front. The problem with `replace` is that you need to remember to bump them manually and that's often forgotten, so only the ones you have 101% confidence should be there.

the go.mod now in master is almost identical to the one in https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/146 ... just some minor drift in openshift/api for example (a couple of commits diff based on when I crafted the go.mod update

I was more granular with the dependency magnet, but that diff is of little consequence.

> 
> I'll just keep this open then and see what is left after I have to rebase

the pkg/* updates are the same to (basically revolving around context change) ... just some minor line order diffs.  Both changes pick up the new library-go factory controller stuff.

I'm closing out my PR in favor of this one.

**Pull request merged**
