### PR TITLE
move openshift controller manager later in CVO payload

### PR DESCRIPTION
**Pull request by deads2k**
nothing earlier than 70 should require openshift apis

### CODE REVIEW

**Comment by bparees** [comment]
/hold

@deads2k i did a more significant renaming here along w/ some new files, so i'd rather just merge that, unless you see issues w/ the metrics enablement i did there:
https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/62

**Comment by deads2k** [comment]
/hold cancel

this is related to fixing out queue.  If it does green, it needs to merge

**Pull request merged**
