### PR TITLE
OCPBUGS-34384: [release-4.16] Disable Rolebindings for Capabilities

### PR DESCRIPTION
**Pull request by adambkaplan**
This is a backport of [OCPBUILD-9](https://issues.redhat.com//browse/OCPBUILD-9) and OCPBUGS-34077 to 4.16. With this change, the default rolebindings controller is disabled permanently. In its place are separate rolebinding controllers that are required for a respective cluster capability. These new controllers were added in OCP 4.16 already.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/label cherry-pick-approved

Cherry pick approved due to customer need.

**Comment by adambkaplan** [comment]
/label backport-risk-assessed

This is a critical issue that needs to land in 4.16 - either .0 or an early z-stream release.

**Comment by adambkaplan** [comment]
/hold

I want to see the "parent" set of PRs merged into an accepted OCP 4.17 payload first.

**Comment by adambkaplan** [comment]
Update: keeping the hold on this PR. Will likely combine with the backport of https://issues.redhat.com/browse/OCPBUGS-34395, whose root cause is also related to the operator.

**Comment by adambkaplan** [comment]
/hold cancel

CI payloads for 4.17 are now "Accepted." Brought in the backport of  [OCPBUGS-34395](https://issues.redhat.com/browse/OCPBUGS-34395)

**Comment by petr-muller** [comment]
Rename for [OCPBUGS-34395](https://issues.redhat.com/browse/OCPBUGS-34395) LGTM

**Review by sayan-biswas — APPROVED** [review]

**Pull request merged**
