### PR TITLE
Bug 1879253: Add provider to user CA ConfigMap target 

### PR DESCRIPTION
**Pull request by adambkaplan**
Add provider information when syncing the proxy TrustedCA ConfigMap to the openshift-controller-manager namespace.

### CODE REVIEW

**Comment by adambkaplan** [comment]
/cc @otaviof 

Note that this PR bumps library-go.

**Comment by soltysh** [comment]
I'd suggest getting rid of one of the dockerfiles, you have 2 and it's confusing.

**Comment by adambkaplan** [comment]
@soltysh PR to remove the rhel7 Dockerfile: https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/176

**Comment by adambkaplan** [comment]
bump @soltysh @mfojtik

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
