### PR TITLE
operator: wait for spec.observedConfig to be fill before installing

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

I suspect that @bparees would prefer not to do this.

**Comment by bparees** [comment]
> I suspect that @bparees would prefer not to do this.

it seems like a hack(to avoid a controller manager restart i assume?), but is there another reason i would prefer not to do it?

**Comment by sttts** [comment]
> it seems like a hack(to avoid a controller manager restart i assume?), but is there another reason i would prefer not to do it?

Why should we install static pods before looking at cluster configuration the installer has put there? I pretty strongly think this would be wrong and asks for inconsistent seconds/minutes until another static pod is installed.

Note: this is not about later runs. It is about cluster config (e.g. network CIDRs) that is put into the cluster early for a reason.

**Comment by bparees** [comment]
@sttts @deads2k is this still at all relevant/needed?

**Comment by coreydaley** [comment]
@sttts @deads2k bump

**Pull request closed without merging**
