### PR TITLE
API-1642: add image pull secret cleanup controller

### PR DESCRIPTION
**Pull request by sanchezl**
Builds on https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/298, adding ImagePullSecretCleanupController.

### CODE REVIEW

**Comment by flavianmissi** [comment]
LGTM
I can tag it once it's rebased

**Comment by flavianmissi** [comment]
/lgtm
test failures look unrelated
/retest

**Comment by flavianmissi** [comment]
LGTM from the registry's POV.
/lgtm

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
