### PR TITLE
Bug 2004127: bump library-go and dependencies

### PR DESCRIPTION
**Pull request by jkhelil**

### CODE REVIEW

**Comment by otaviof** [comment]
@jkhelil have you ran `go mod tidy` as well? I'm running it here and it removed one dependency, i.e:
```sh
$ go mod tidy
# ...

$ git diff go.mod
diff --git a/go.mod b/go.mod
index 4b78afbd..bc0039b6 100644
--- a/go.mod
+++ b/go.mod
@@ -3,7 +3,6 @@ module github.com/openshift/cluster-openshift-controller-manager-operator
 go 1.13

 require (
-	github.com/fsnotify/fsnotify v1.4.9 // indirect
 	github.com/ghodss/yaml v1.0.0
 	github.com/go-bindata/go-bindata v3.1.2+incompatible
 	github.com/google/gofuzz v1.2.0 // indirect
```

So, do we need `github.com/fsnotify/fsnotify` after all?

**Comment by jkhelil** [comment]
> @jkhelil have you ran `go mod tidy` as well? I'm running it here and it removed one dependency, i.e:
> 
> ```shell
> $ go mod tidy
> # ...
> 
> $ git diff go.mod
> diff --git a/go.mod b/go.mod
> index 4b78afbd..bc0039b6 100644
> --- a/go.mod
> +++ b/go.mod
> @@ -3,7 +3,6 @@ module github.com/openshift/cluster-openshift-controller-manager-operator
>  go 1.13
> 
>  require (
> -	github.com/fsnotify/fsnotify v1.4.9 // indirect
>  	github.com/ghodss/yaml v1.0.0
>  	github.com/go-bindata/go-bindata v3.1.2+incompatible
>  	github.com/google/gofuzz v1.2.0 // indirect
> ```
> 
> So, do we need `github.com/fsnotify/fsnotify` after all?

@otaviof  this dependency is not added by this commit. I am removing it with go mod tidy

**Comment by adambkaplan** [comment]
/test e2e-aws

Retesting to verify if flake reappears

**Review by adambkaplan — APPROVED** [review]
/approve

Flakes unrelated to this PR.

**Pull request merged**
