### PR TITLE
Fix scripts

### PR DESCRIPTION
**Pull request by tnozicka**

### CODE REVIEW

**Comment by deads2k** [comment]
Is this going to allow us to remove the CI bit where we are doing go get before the script call?

**Comment by tnozicka** [comment]
not this one in particular but if we vendor those we can use the same pattern and avoid `go get` at all

this one is just a fix for newer go that don't need GOPATH set so it's not exported by default and the script fails

**Comment by deads2k** [comment]
> not this one in particular but if we vendor those we can use the same pattern and avoid `go get` at all

I don't want to vendor things that are not code dependencies, but I am ok `go get`-ing things.

**Pull request merged**
