### PR TITLE
Switch openshift/ocm-o to go1.11

### PR DESCRIPTION
**Pull request by soltysh**
/assign @tnozicka @sttts
Requires https://github.com/openshift/release/pull/3489

### CODE REVIEW

**Comment by adambkaplan** [comment]
For clarity the golang builder in the Dockerfiles should be changed to golang-1.11
https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/master/Dockerfile#L1
https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/master/Dockerfile.rhel7#L1

**Comment by soltysh** [comment]
@adambkaplan good point, lemme update those right away

**Comment by soltysh** [comment]
@adambkaplan mind re-tagging

**Comment by coreydaley** [comment]
I am working to address this test failure in #87 , just an FYI

**Pull request merged**
