### PR TITLE
Bug 1907948: BUILD-149: bump(*): k8s 1.20.1-rc.0

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Review by adambkaplan — CHANGES_REQUESTED** [review]
Please amend the commit to include a message of which items were bumped. Looks like you did an update of openshift/api.

Also - did you run a `go mod tidy`? Noticed the indirect import of k8s.io/apiserver.

**Comment by gabemontero** [comment]
> Please amend the commit to include a message of which items were bumped. Looks like you did an update of openshift/api.

openshift/api now noted in the commit message @adambkaplan 

> 
> Also - did you run a `go mod tidy`? Noticed the indirect import of k8s.io/apiserver.

`go mod tidy` produces no changes for me - just ran it again .... the k8s.io/apiserver change was needed to force it to 1.20 as well, which was needed to get k8s items we were already importing to compile @adambkaplan

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
