### PR TITLE
Bug 2111979: Set openshift.io/run-level to nil in openshift-controller-manager nam…

### PR DESCRIPTION
**Pull request by jkhelil**
…espace

### CODE REVIEW

**Comment by gabemontero** [comment]
/assign @coreydaley 

@jkhelil Corey is an approver in the owners file, so he can apply the approve label.  Neither Adam no I are approvers in the owners file.

FWIW I have no familiarity with the run-level label, so have no expertise to lend to this change.

**Comment by coreydaley** [comment]
/approve
/assign @bparees 
for lgtm

**Pull request merged**
