### PR TITLE
OCPBUGS-23624: Add .snyk file to exclude vendor and ignore unit tests

### PR DESCRIPTION
**Pull request by ingvagabund**
SSIA

### CODE REVIEW

**Comment by adambkaplan** [comment]
@ingvagabund please revert/update this PR so we do not exclude the entire vendor tree.

Only vetted "false positives" should be put in the `.snyk` exclude file (with documented justification).

**Comment by ardaguclu** [comment]
AFAIK Exclusion of specific files do not work on synk.

**Pull request merged**
