### PR TITLE
bump(*): pick up https://github.com/openshift/library-go/pull/284

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero @adambkaplan bump

**Comment by bparees** [comment]
> Interesting that only the glide.lock was picked up, and not whatever associated glide.yaml change accompanied it

there was no glide.yaml change, i was just pulling in updated versions of the deps from the repos/branches we point to.

**Comment by gabemontero** [comment]
> there was no glide.yaml change, i was just pulling in updated versions of
> the deps from the repos/branches we point to.
>
I guess I would expect those deps to cut new versions as things change, but
in retrospect, sure, they could be bug fixes
to an existing tag, etc.

**Pull request merged**
